/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-04 08:17:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1683082112989L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1683188087862L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Script to Activate the Carousel -->\r\n");
      out.write("<script>\r\n");
      out.write("        $('.carousel').carousel({\r\n");
      out.write("            interval: 2000 //changes the speed\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-idth, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Welcome to MyWorld</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"/MyWeb/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"/MyWeb/css/business-casual.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Nanum+Pen+Script&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"/MyWeb/js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"/MyWeb/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<div class=\"brand\">\r\n");
      out.write("		<a href=\"/MyWeb\">My Web</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"address-bar\">Welcome to MyWorld</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("					data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("					<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("						class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("						class=\"icon-bar\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"/Test\">My First Web</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\"\r\n");
      out.write("				id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("				<ul class=\"nav navbar-nav\">\r\n");
      out.write("\r\n");
      out.write("					<li><a href=\"/Myweb\">HOME</a></li>\r\n");
      out.write("					<li><a href=\"\">Member</a></li>\r\n");
      out.write("					<li><a href=\"\">BOARD</a></li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"/MyWeb/loginPage.user\">LOGIN</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"/MyWeb/joinPage.user\" style=\"color: red\">JOIN</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- /.navbar-collapse -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- /.container -->\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- end header -->\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row \">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-6 text-center\">\r\n");
      out.write("					<div id=\"carousel-example-generic\" class=\"carousel slide\"\r\n");
      out.write("						data-ride=\"carousel\">\r\n");
      out.write("						<!-- data-ride=\"carousel\" 자동 슬라이드 기능 -->\r\n");
      out.write("\r\n");
      out.write("						<ol class=\"carousel-indicators hidden-xs\">\r\n");
      out.write("							<li data-target=\"#carousel-example-generic\" data-slide-to=\"0\"\r\n");
      out.write("								class=\"active\"></li>\r\n");
      out.write("							<li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\r\n");
      out.write("							<li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\r\n");
      out.write("\r\n");
      out.write("						</ol>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"carousel-inner\">\r\n");
      out.write("							<div class=\"item active\">\r\n");
      out.write("								<img class=\"img-responsive img-full\" src=\"img/1.jpg\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"item\">\r\n");
      out.write("								<img class=\"img-responsive img-full\" src=\"img/2.jpg\">\r\n");
      out.write("								<!-- img-full 옵션 class -->\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"item\">\r\n");
      out.write("								<img class=\"img-responsive img-full\" src=\"img/5.jpg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<a class=\"left carousel-control\" href=\"#carousel-example-generic\"\r\n");
      out.write("							data-slide=\"prev\"> <span class=\"icon-prev\"></span>\r\n");
      out.write("						</a> <a class=\"right carousel-control\"\r\n");
      out.write("							href=\"#carousel-example-generic\" data-slide=\"next\"> <span\r\n");
      out.write("							class=\"icon-next\"></span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-6 text-center\">\r\n");
      out.write("\r\n");
      out.write("					<h2>영상 링크</h2>\r\n");
      out.write("					<p>원하는 영상을 링크해 보세요.</p>\r\n");
      out.write("					<hr>\r\n");
      out.write("					<h3>영상 자동재생</h3>\r\n");
      out.write("					<iframe width=\"100%\" height=\"485px\"\r\n");
      out.write("						src=\"https://www.youtube.com/embed/MEkaqZecpUQ\" frameborder=\"0\"\r\n");
      out.write("						allow=\"accelerometer; encrypted-media; gyroscope; picture-in-picture\"\r\n");
      out.write("						allowfullscreen></iframe>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<hr>\r\n");
      out.write("					<h2 class=\"intro-text text-center\">\r\n");
      out.write("						Jsp Web Programming <strong>공지 사항</strong>\r\n");
      out.write("					</h2>\r\n");
      out.write("					<hr>\r\n");
      out.write("					<div class=\"inner\" align=\"center\">\r\n");
      out.write("						<img class=\"img-responsive img-center\" src=\"img/intro.jpg\" alt=\"\">\r\n");
      out.write("						<!-- img-border -->\r\n");
      out.write("\r\n");
      out.write("						<hr class=\"visible-xs\">\r\n");
      out.write("\r\n");
      out.write("						<p>1. 공지사항을 작성하는 란입니다.</p>\r\n");
      out.write("						<p>2. 자유롭게 작성 해 보세요.</p>\r\n");
      out.write("						<p>3. -----------------------------------</p>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- /.container -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!--Footer-->\r\n");
      out.write("			<footer>\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-md-5\">\r\n");
      out.write("							<span class=\"copyright\"> Copyright &copy; By Jsp\r\n");
      out.write("								Programming </span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3\">\r\n");
      out.write("							<ul class=\"list-inline social\">\r\n");
      out.write("								<li class=\"list-inline-item\"><a class=\"facebook-btn\"\r\n");
      out.write("									href=\"\"> <img src=\"/MyWeb/img/facebook.PNG\" alt=\"페이스북 링크\">\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li class=\"list-inline-item\"><a class=\"instagram-btn\"\r\n");
      out.write("									href=\"\"> <img src=\"/MyWeb/img/insta.PNG\" alt=\"인스타 링크\">\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li class=\"list-inline-item\"><a class=\"twitter-btn\" href=\"\">\r\n");
      out.write("										<img src=\"/MyWeb/img/twitter.PNG\" alt=\"트위터 링크\">\r\n");
      out.write("								</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<span class=\"contact\"> Email: stephen4951@gmail.com </span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
